name: CI/CD Workflow

on:
  push:
    branches: ["development"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update Odoo and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
