name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull changes from development branch
      run: git pull origin development

    - name: Restart Odoo server
      run: sudo service odoo-server restart
